"""Root 2

Revision ID: 9b7598866b78
Revises: 3ca86d18f500
Create Date: 2023-05-26 21:38:10.441014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7598866b78'
down_revision = '3ca86d18f500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
